### ISSUE TITLE
Ranks table stuck when chat is opened

### ISSUE THREAD

**Issue by Sm1thTV** [GrantJL/rl-lobby-ranks#4]
**Describe the defect / bug**
As soon as I open the team chat or the ingame chat generally, there is the possibility, that the table dont hide again if its opened.

**Expected behavior**
It should disappear again.

**Comment by GrantJL** [comment]
I believe is already fixed in v1.1.3 or v1.1.4.
I have update the plugin on bakkesplugins,com, but it looks like it is taking a while for the website to update the plugin.

I have instead added a release to the GitHub page.
You can follow the install instructions there: [GitHub - LobbyRanks v1.1.4](https://github.com/GrantJL/rl-lobby-ranks/releases/tag/v1.1.4.4)

I will close this issue out now, feel free to comment here, or open another if you have further issues.
